import type { Vehicle, Testimonial, FAQ } from '@/types';

export const MOCK_VEHICLES: any[] = [
  {
    id: 'a0000000-0000-0000-0000-000000000001',
    slug: 'maruti-suzuki-swift-vxi-2021',
    make: 'Maruti Suzuki',
    model: 'Swift',
    variant: 'VXI',
    year: 2021,
    registration_year: 2021,
    price: 595000,
    original_price: 650000,
    mileage: 28000,
    fuel_type: 'Petrol',
    transmission: 'Manual',
    body_type: 'Hatchback',
    colour: 'Magma Grey',
    seating_capacity: 5,
    engine_cc: 1197,
    engine_description: '1.2L K12N Petrol',
    location: 'Delhi',
    registration_state: 'Delhi',
    ownership: 1,
    insurance_status: 'Comprehensive',
    rc_available: true,
    puc_available: true,
    accident_history: false,
    service_history: 'Full Service History',
    vehicle_category: 'Car',
    description: 'Well-maintained first-owner Swift VXI. All service records available. Tyres 70% life remaining.',
    is_featured: true,
    is_new_arrival: true,
    is_hot_deal: false,
    is_price_drop: true,
    status: 'Active',
    availability: 'Available',
    view_count: 45,
    enquiry_count: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    main_image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80',
    vehicle_images: [
      { id: '1', url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80', is_main: true, sort_order: 0, thumbnail_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=200&q=80' },
      { id: '2', url: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?w=800&q=80', is_main: false, sort_order: 1, thumbnail_url: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?w=200&q=80' },
    ],
  },
  {
    id: 'a0000000-0000-0000-0000-000000000002',
    slug: 'hyundai-creta-sx-2022',
    make: 'Hyundai',
    model: 'Creta',
    variant: 'SX',
    year: 2022,
    registration_year: 2022,
    price: 1350000,
    original_price: null,
    mileage: 22000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    colour: 'Typhoon Silver',
    seating_capacity: 5,
    engine_cc: 1497,
    engine_description: '1.5L MPi Petrol',
    location: 'Gurugram',
    registration_state: 'Haryana',
    ownership: 1,
    insurance_status: 'Comprehensive',
    rc_available: true,
    puc_available: true,
    accident_history: false,
    service_history: 'Full Service History',
    vehicle_category: 'SUV',
    description: 'Single owner Creta SX Automatic. Sunroof, connected car tech, smart features.',
    is_featured: true,
    is_new_arrival: true,
    is_hot_deal: true,
    is_price_drop: false,
    status: 'Active',
    availability: 'Available',
    view_count: 89,
    enquiry_count: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    main_image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
    vehicle_images: [
      { id: '3', url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80', is_main: true, sort_order: 0, thumbnail_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=200&q=80' },
    ],
  },
  {
    id: 'a0000000-0000-0000-0000-000000000003',
    slug: 'maruti-suzuki-dzire-vxi-2022',
    make: 'Maruti Suzuki',
    model: 'Dzire',
    variant: 'VXI',
    year: 2022,
    registration_year: 2022,
    price: 695000,
    original_price: 750000,
    mileage: 18500,
    fuel_type: 'Petrol',
    transmission: 'Manual',
    body_type: 'Sedan',
    colour: 'Oxford Blue',
    seating_capacity: 5,
    engine_cc: 1197,
    engine_description: '1.2L K12N Petrol',
    location: 'Delhi',
    registration_state: 'Delhi',
    ownership: 1,
    insurance_status: 'Comprehensive',
    rc_available: true,
    puc_available: true,
    accident_history: false,
    service_history: 'Full Service History',
    vehicle_category: 'Car',
    description: 'Corporate driven single owner Dzire. Absolute mint condition.',
    is_featured: false,
    is_new_arrival: false,
    is_hot_deal: true,
    is_price_drop: true,
    status: 'Active',
    availability: 'Available',
    view_count: 67,
    enquiry_count: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    main_image_url: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80',
    vehicle_images: [
      { id: '4', url: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80', is_main: true, sort_order: 0, thumbnail_url: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=200&q=80' },
    ],
  },
  {
    id: 'a0000000-0000-0000-0000-000000000004',
    slug: 'toyota-innova-crysta-24-vx-2020',
    make: 'Toyota',
    model: 'Innova Crysta',
    variant: '2.4 VX 7 Str',
    year: 2020,
    registration_year: 2020,
    price: 1875000,
    original_price: 1950000,
    mileage: 62000,
    fuel_type: 'Diesel',
    transmission: 'Manual',
    body_type: 'MUV',
    colour: 'Super White',
    seating_capacity: 7,
    engine_cc: 2393,
    engine_description: '2.4L 2GD-FTV Diesel',
    location: 'Delhi',
    registration_state: 'Delhi',
    ownership: 1,
    insurance_status: 'Comprehensive',
    rc_available: true,
    puc_available: true,
    accident_history: false,
    service_history: 'Full Service History',
    vehicle_category: 'Commercial',
    description: 'vx model Innova Crysta. Showroom service history. Genuine running.',
    is_featured: true,
    is_new_arrival: false,
    is_hot_deal: false,
    is_price_drop: false,
    status: 'Active',
    availability: 'Available',
    view_count: 104,
    enquiry_count: 11,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    main_image_url: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80',
    vehicle_images: [
      { id: '5', url: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80', is_main: true, sort_order: 0, thumbnail_url: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=200&q=80' },
    ],
  },
];

export const MOCK_TESTIMONIALS: any[] = [
  {
    id: 't1',
    customer_name: 'Rajesh Kumar',
    customer_location: 'Janakpuri, Delhi',
    review: 'Great service. I bought a Swift Dzire and the process was absolutely transparent. No hidden charges and paperwork was completed quickly.',
    rating: 5,
    vehicle_purchased: 'Maruti Suzuki Dzire',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    sort_order: 1,
  },
  {
    id: 't2',
    customer_name: 'Amit Sharma',
    customer_location: 'Gurugram',
    review: 'Very professional dealers. They helped me evaluate my car and bought it within 24 hours at a very fair price.',
    rating: 5,
    vehicle_purchased: 'Hyundai Verna',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    sort_order: 2,
  },
  {
    id: 't3',
    customer_name: 'Priyanka Sen',
    customer_location: 'Noida',
    review: 'Friendly staff and reliable advice. Got an excellent deal on a pre-owned Creta. Highly recommend AutoCapital Wheels.',
    rating: 4,
    vehicle_purchased: 'Hyundai Creta',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    sort_order: 3,
  },
];

export const MOCK_FAQS: any[] = [
  {
    id: 'f1',
    question: 'How do you verify the condition of the cars?',
    answer: 'Every car listed on AutoCapital Wheels undergoes inspection. We check mechanical parts, document authenticity, service history, and ensure the vehicle is clean and ready.',
    category: 'General',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    sort_order: 1,
  },
  {
    id: 'f2',
    question: 'Can I request a test drive?',
    answer: 'Yes! Simply click "Request Test Drive" or "Get Quotation" on any vehicle card, fill in your phone number, and our team will contact you to schedule it.',
    category: 'Buying',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    sort_order: 2,
  },
  {
    id: 'f3',
    question: 'What documentation do you provide?',
    answer: 'We assist with registration transfer (RC transfer), verify insurance validity, PUC status, and check past history logs so you get a completely clear ownership transfer.',
    category: 'Documentation',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    sort_order: 3,
  },
];
